version: "3"
services:
  api-example:
    image: java-api-example
    ports:
      - 8080:8080
  mongodb-sample:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-sample-volume:/data/db

  mongo-express-sample:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-sample
#volume at services level
volumes:
  mongo-sample-volume:
    driver: local #additonal information for docke to create on local


