pipeline {
    agent any
    tools {
        maven 'Maven 3.9.6'
    }
    parameters {
        string(name: 'Name', defaultValue:'', description: 'What is your name?')
        choice(name: 'VERSION', choices:['1.0','2.0','3.0'])
        booleanParam(name: 'runTests', defaultValue: true, description: 'Do you want to run Tests?')
    }
    stages {
        stage("Build Jar") {
            steps {
                echo "Building..."
                sh 'mvn -f java-api/pom.xml clean'
            }
        }
        stage("Test") {
            when {
                expression {
                    params.runTests
                }
            }
            steps {
                echo "Testing..."
                sh 'mvn -f java-api/pom.xml test'
            }
        }
        stage("Build Docker Image") {
            steps {
                echo "Building Docker Image ... "
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub_mazhar', passwordVariable: 'PASSWORD', usernameVariable:'USER_NAME')]) {
                        dir('java-api') {
                            sh 'docker build -t api-example:java-0.2 .'
                            sh 'docker tag api-example:java-2.0 javaarchitect/api-example:java-2.0'
                            sh 'echo $PASSWORD | docker login -u $USER_NAME --password-stdin'
                            sh 'docker push javaarchitect/api-example:java-2.0'
                        }
                        
                    }
                }
            }
        }
        stage("Deploy") {
            steps {
                echo "Deploying..."
            }
        }
    }
}
